annuaire/urls.py
# -*- encoding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns('annuaire.views',
    url(r'^$', 'accueil',name="aruca_home"),
    url(r'^chercheurs/$', 'list_chercheur',name="list_chercheur"),
    url(r'^chercheurs/(?P<id>[-\w]+)/$', 'chercheur_detail',name="chercheur_detail"),
    # url(r'^inscription-chercheur/$', 'InscriptionChercheur', name='chercheur_inscription'),
    url(r'^chercheur/activation/(?P<id_base36>.*)/(?P<token>.*)/$','activation', name='chercheur_activation'),
    url(r'^espace_utilisateur/$', 'perso'),
    url(r'^chercheur/edit/$', 'edit'),
    url(r'^chercheur/desinscription/$', 'desinscription'),
    url(r'^validation/$', TemplateView.as_view(template_name='validation.html'), name='Validation_chercheur'),
    url(r'^equipes/$', 'list_equipe'),
    url(r'^equipes/(?P<id>[-\w]+)/$', 'equipe',name="team"),
    url(r'^inscription-equipe/$', 'InscriptionEquipe',name="insc_Equipe"),
    url(r'^validation_equipe/$', TemplateView.as_view(template_name='validation_equipe.html'), name='Validation_equipe'),
    url(r'^connexion/$', 'login', kwargs={'template_name': 'login.html'}, name='login'),
    url(r'^actualites/$', 'actual',name='actualites'),
    url(r'^appels_offres/$', 'aos',name='appelO'),
    url(r'^liens_utiles/$', 'usefull_link',name='usefull_link'),
    url(r'presentation/$', 'presentation',name='presentation'),
    url(r'equipe_laboratoire/$', 'equipe_laboratoire',name='equipe_laboratoire'),

    # Espace utilisateurs
    url(r'^creation_compte/$', 'creation_compte',name='creation_compte'),
    # Espace utilisateurs
)

urlpatterns += patterns ('',
    url(r'^deconnexion/$', 'django.contrib.auth.views.logout', kwargs={'template_name': 'accueil.html'}, name='chercheurs_logout'),
    url(r'^chercheur/changement-mdp/$', 'annuaire.views.password_change',
        kwargs={
            'template_name': 'password_change_form.html',
            'post_change_redirect': '/chercheur/changement-mdp-fini/'
        },
        name='chercheurs-password-change'),
    url(r'^chercheur/changement-mdp-fini/$',
        'django.contrib.auth.views.password_change_done',
        kwargs={'template_name': 'password_change_done.html'},
        name='chercheurs-password-change-done'),
    # Oublié mot de passe
    url(r'^chercheur/oubli-mdp/$', 'django.contrib.auth.views.password_reset', kwargs={
            'template_name': 'password_reset_form.html',
            'email_template_name': 'password_reset_email.txt',
            'post_reset_redirect': '/chercheur/oubli-mdp-envoye/'
        },
        name='chercheurs-password-reset'),
    url(r'^chercheur/oubli-mdp-envoye/$', 'django.contrib.auth.views.password_reset_done', kwargs={'template_name': 'password_reset_done.html'},
        name='chercheurs-password-reset-done'),
    url(r'^chercheur/oubli-mdp-retour/(?P<uidb36>.*)/(?P<token>.*)/$', 'django.contrib.auth.views.password_reset_confirm', kwargs={'template_name': 'password_reset_confirm.html'},
        name='chercheurs_password_reset_confirm'),
    url(r'^chercheur/oubli-mdp-fini/$', 'django.contrib.auth.views.password_reset_complete', kwargs={'template_name': 'password_reset_complete.html'}),
)

appels/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns('appels.views',
    url(r'appels-offre/$', 'appel_offre'),
    url(r'^appels-offre/(?P<slug>[-\w]+)/$', 'appel_offre_detail'),
)

aruca_auf_org/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from filebrowser.sites import site
from feeds import DerniersAjouts

admin.autodiscover()

urlpatterns = i18n_patterns('',
    # url(r'^$','views.acc'),
    url(r'^$', include('ciec_portail.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^flux-rss/$', DerniersAjouts()),
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    #Apps urls
    url(r'^aruca/', include('annuaire.urls')),
    url(r'^appels/', include('appels.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^photos/', include('photos.urls')),
    url(r'^portail/', include('ciec_portail.urls')),
    #Apps urls
    #search
    url(r'^recherche/$', 'views.search'),
    url(r'^a-propos/$', 'views.propos'),
    url(r'^aide/$', 'views.help'),
    url(r'^liens-utiles/$', 'views.useful'),
    #search
    (r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^t/', include('cms.urls')),

)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

annuaire/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.contrib.auth.forms import AuthenticationForm as DjangoAuthenticationForm, SetPasswordForm as DjangoSetPasswordForm
from django.forms.models import inlineformset_factory
from .models import *

class SendPasswordForm(forms.Form):
    email = forms.EmailField(required=True, label="Adresse électronique")
    def clean_email(self):
        cleaned_data = self.cleaned_data
        email = cleaned_data.get("email")
        if email:
            try:
                Chercheur.objects.get(courriel=email)
            except:
                raise forms.ValidationError("Cette adresse n'existe pas dans notre base de données.")
        return email

class SetPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(), required=True, label="Mot de passe")
    password_repeat = forms.CharField(widget=forms.PasswordInput(), required=True, label="Confirmez votre mot de passe")

    def clean_password_repeat(self):
        cleaned_data = self.cleaned_data
        password = cleaned_data.get("password")
        password_repeat = cleaned_data.get("password_repeat")
        if password and password_repeat:
            if password != password_repeat:
                raise forms.ValidationError("Les mots de passe ne concordent pas")
        return password_repeat

class AuthenticationForm(DjangoAuthenticationForm):
    username = forms.CharField(label='Courriel')

class InscriptionCForm(forms.ModelForm):
    class Meta:
        model = Chercheur
        # fields = ['langue','etablissement','etablissement_autre_nom','etablissement_autre_pays','genre','nom',
        #             'prenom','courriel','afficher_courriel','site','telephone','telecopie','axe','mots_cles',
        #             'diplome','discipline','theme_recherche','equipement','laboratoire','terrain' ,'valorisation',
        #             'partenaires','doctorants', 'stagiaire' , 'publicationsInternational','publicationsAutre',
        #             'publicationsColloc', 'communication', 'equipe', 'domaine', 'actif'
        #         ]
        fields = ('courriel','afficher_courriel',)
    def clean_courriel(self):
        """On veut s'assurer qu'il n'y ait pas d'autre utilisateur actif
           avec le même courriel."""
        courriel = self.cleaned_data['courriel']
        print (courriel)
        existing = Chercheur.objects.filter(courriel=courriel, actif=True)
        if self.instance and self.instance.id:
            existing = existing.exclude(id=self.instance.id)

        else:
            # Nouveau chercheur
            user = User.objects.filter(is_active=True, email=courriel)
            if user.count():
                raise forms.ValidationError('Il existe déjà une fiche pour cette adresse électronique')

        if existing.count():
            raise forms.ValidationError('Il existe déjà une fiche pour cette adresse électronique')
        return courriel

class TheseForm(forms.ModelForm):
    class Meta:
        model = These
        fields = ('titre', 'annee', 'directeur', 'etablissement', 'nb_pages')

class PublicationForm(forms.ModelForm):
    class Meta:
        model = PublicationsMajeur
        fields = ('auteurs', 'titre', 'revue', 'annee', 'nb_pages')

PublicationFormSet = inlineformset_factory(Chercheur, PublicationsMajeur, form=PublicationForm, extra=1)

class attestationForm(forms.Form):
    attestation = forms.BooleanField(required=True,label="J'atteste sur l'honneur l'exactitude des renseignements fournis sur le formulaire d'inscription et j'accepte leur publication en ligne.")

class ChercheurFormGroup(object):

    def __init__(self, data=None, chercheur=None):
        try:
            these = chercheur and chercheur.these
        except These.DoesNotExist:
            these = These()
        self.chercheur = InscriptionCForm(data=data, prefix='chercheur', instance=chercheur)
        # self.these = TheseForm(data=data, prefix='these', instance=these)
        # self.attestation = attestationForm(data=data, prefix='attestation')
        # self.publications = PublicationFormSet(data=data, prefix='publication', instance=chercheur)

    @property
    def has_errors(self):
        return bool(self.chercheur.errors) #or self.these.errors or self.publications.errors or self.attestation.errors

    def is_valid(self):
        return self.chercheur.is_valid() #and self.these.is_valid() and self.publications.is_valid() and self.attestation.is_valid()

    def save(self):
        if self.is_valid():

            # Enregistrer d'abord le chercheur lui-même.
            self.chercheur.save()

            # Puis les objets qui ont des clés étrangères vers nous
            # puisqu'on a besoin d'un id.
            chercheur = self.chercheur.instance
            # self.these.instance.chercheur = chercheur
            # self.these.save()
            # self.publications.instance = chercheur
            # self.publications.save()
            return self.chercheur.instance


class InscriptionEForm(forms.ModelForm):
    class Meta:
        model = Equipe
        exclude = ['date_mod','date_pub']

class PublicationFormEquipe(forms.ModelForm):
    class Meta:
        model = PublicationsMajeurEquipe
        fields = ('auteurs', 'titre', 'revue', 'annee', 'nb_pages')

PublicationFormSetEquipe = inlineformset_factory(Equipe, PublicationsMajeurEquipe, form=PublicationFormEquipe, extra=1)

class EquipeFormGroup(object):

    def __init__(self, data=None, equipe=None):
        self.equipe = InscriptionEForm(data=data, prefix='chercheur', instance=equipe)
        self.attestation = attestationForm(data=data, prefix='attestation')
        self.publications = PublicationFormSetEquipe(data=data, prefix='publication', instance=equipe)

    @property
    def has_errors(self):
        return bool(self.equipe.errors or self.publications.errors or self.attestation.errors)

    def is_valid(self):
        return self.equipe.is_valid() and self.publications.is_valid() and self.attestation.is_valid()

    def save(self):
        if self.is_valid():

            # Enregistrer equipe.
            self.equipe.save()

            # Puis les objets qui ont des clés étrangères vers nous
            # puisqu'on a besoin d'un id.
            equipe = self.equipe.instance
            self.publications.instance = equipe
            self.publications.save()
            return self.equipe.instance


class ActualitesAOForm(forms.ModelForm):
    class Meta:
        model = ActualitesAO
        fields = ('type_artl','titre_artl','description_artl','image_artl','lien_artl')

class ContactForm(forms.Form):
    nom = forms.CharField(max_length=200)
    email = forms.EmailField(max_length=200, required=False)
    sujet = forms.CharField(max_length=200)
    message = forms.CharField(widget=forms.Textarea)



class LaboEquipForm(forms.ModelForm):
    class Meta:
        model = LaboEquip
        exclude = ('show',)

annuaire/templates/accueil_true.html
{% extends "base.html" %}
{% load i18n cms_tags%}
{% block Contenu %}

{% if slider_list%}

        {% with slider_list as item_list %}
                <div id="slide">
						<div class="slider-wrapper theme-default">
							<div id="slider" class="nivoSlider">
                            {% for item in item_list %}
                            	 {% if item.lien %}<a href="{{ item.lien }}">{% endif %}<img src="{{ MEDIA_URL }}{{ item.image}}" alt="{{ item.titre }}" title="{{ item.titre }}" />{% if item.lien %}</a>{% endif %}
                           {% endfor %}
                    	   </div>
				       </div>
			   </div>
         {% endwith %}

{% endif %}

						<div id="texte">

                            

						  </div>

{% endblock %}

annuaire/templates/chercheurs.html
{% extends "base.html" %}
{% load i18n pagination_tags%}

{% block Contenu %}
<div id="texte">
<!--<h3>Liste des chercheurs</h3>-->

<div class="chercheur">
   <h3>{% trans "Filtrez vos recherches" %}</h3>
   <form method="get" action="">
  	{{ ChercherCForm.as_p }}
  	<input type="submit" class="bouton" value="Rechercher" />
  </form>
</div>

<p>{{message}}</p>

{% if chercheurs_list %}
	
    {% with chercheurs_list as item_list %}

        {% for item in item_list %}
        	<div class="chercheur">
            	<h3><a href="{{ item.get_absolute_url }}">{{ item.nom }} {{ item.prenom }}</a></h3>
                <p><span>{% trans "Université" %} :</span> {{ item.etablissement }}, {{ item.etablissement_autre_nom }}</p>
                <p><span>{% trans "Enseignements dispensés" %} :</span> {{ item.discipline }}</p>
                <p><span>{% trans "Mots-clefs" %} :</span> {{ item.mots_cles }}</p>
           </div>
		{% endfor %}

    {% endwith %}
    
{% else %}
    <p>{% trans "Aucun chercheur" %}</p>
{% endif %}

{% paginate %}
</div>

{% endblock %}

annuaire/templates/equipes.html
{% extends "base.html" %}
{% load i18n pagination_tags%}

{% block Contenu %}
<div id="texte">
<!--<h3>Liste des chercheurs</h3>-->

<div class="chercheur">
   <h3>{% trans "Filtrez vos rechercher" %}</h3>
   <form method="get" action="">
  	{{ EquipeCForm.as_p }}
  	<input type="submit" class="bouton" value="Rechercher" />
  </form>
</div>

<p>{{message}}</p>

{% if equipe_list %}
	
    {% with equipe_list as item_list %}

        {% for item in item_list %}
        	<div class="chercheur">
            	<h3><a href="{{ item.get_absolute_url }}">{{ item.nom }} {{ item.prenom }}</a></h3>
                <p><span>{% trans "Université" %} :</span> {{ item.etablissement }}, {{ item.etablissement_autre_nom }}</p>
                <p><span>{% trans "Intitulé de l'équipe" %} :</span> {{ item.intitule }}</p>
                <p><span>{% trans "Mots-clefs" %} :</span> {{ item.mots_cles }}</p>
           </div>
		{% endfor %}

    {% endwith %}
    
{% else %}
    <p>{% trans "Aucune équipe" %}</p>
{% endif %}

{% paginate %}
</div>

{% endblock %}

annuaire/templates/inscriptionC.html
{% extends "base.html" %}
{% load i18n %}

{% block Contenu %}

<div id="texte">
<h3>Inscription</h3>

        	<div class="chercheur">

                <form action="" method="POST">
                   <!-- /annuaire/inscription-chercheur/ -->
                    {% csrf_token %}
                    {% if forms.chercheur.errors %}<ul class="errorlist"><li>{% trans "Des erreurs ne permettent pas de s'inscrire." %}</li></ul>{% endif %}

                    <h3 style="margin-bottom: 28px;">{% trans "Propriété de la Fiche" %}</h3>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.langue.errors }}
                            <label for="id_subject">{% trans "Langue" %} <span class="requis">*</span>:</label>
                            {{ forms.chercheur.langue }}
                        </div>

                    <h3 style="margin: 10px 0px 28px 0px">{% trans "Etablissement" %}</h3>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.etablissement.errors }}
                            <label for="id_message">{% trans "Université" %} :</label>
                            {{ forms.chercheur.etablissement }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.etablissement_autre_nom.errors }}
                            <label for="id_sender">{% trans "Faculté/institut/école" %} :</label>
                            {{ forms.chercheur.etablissement_autre_nom }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.etablissement_autre_pays.errors }}
                            <label for="id_cc_myself">{% trans "Pays" %} :</label>
                            {{ forms.chercheur.etablissement_autre_pays }}
                        </div>

                    <h3 style="margin: 10px 0px 28px 0px">{% trans "Informations sur le chercheur" %}</h3>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.genre.errors }}
                            <label for="id_message">{% trans "Genre" %} <span class="requis">*</span>:</label>
                            {{ forms.chercheur.genre }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.nom.errors }}
                            <label for="id_sender">{% trans "Nom" %} <span class="requis">*</span>:</label>
                            {{ forms.chercheur.nom }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.prenom.errors }}
                            <label for="id_cc_myself">{% trans "Prénom" %} <span class="requis">*</span>:</label>
                            {{ forms.chercheur.prenom }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.courriel.errors }}
                            <label for="id_sender">{% trans "Courriel" %} <span class="requis">*</span>:</label>
                            {{ forms.chercheur.courriel }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.afficher_courriel.errors }}
                            <label for="id_cc_myself">{% trans "Afficher courriel" %} :</label>
                            {{ forms.chercheur.afficher_courriel }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.site.errors }}
                            <label for="id_sender">{% trans "Site internet" %} :</label>
                            {{ forms.chercheur.site }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.telephone.errors }}
                            <label for="id_cc_myself">{% trans "Numéro de téléphone" %} :</label>
                            {{ forms.chercheur.telephone }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.telecopie.errors }}
                            <label for="id_sender">{% trans "Numéro de télécopie" %} :</label>
                            {{ forms.chercheur.telecopie }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.diplome.errors }}
                            <label for="id_cc_myself">{% trans "Diplôme le plus élevé" %} :</label>
                            {{ forms.chercheur.diplome }}
                        </div>

                    <h3 style="margin: 10px 0px 28px 0px">{% trans "Enseignements et Recherche" %}</h3>
			<div class="fieldWrapper">
                            {{ forms.chercheur.discipline.errors }}
                            <label for="id_message">{% trans "Enseignements dispensés" %} :</label>
                            {{ forms.chercheur.discipline }}
                        </div>
                    	<div class="fieldWrapper">
                            {{ forms.chercheur.axe.errors }}
                            <label for="id_message">{% trans "Axe de recherche" %} <span class="requis">*</span>:</label>
                            {{ forms.chercheur.axe }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.theme_recherche.errors }}
                            <label for="id_sender">{% trans "Problématique et description de la recherche" %} :</label>
                            {{ forms.chercheur.theme_recherche }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.mots_cles.errors }}
                            <label for="id_cc_myself">{% trans "Mots-clés" %} :</label>
                            {{ forms.chercheur.mots_cles }}
                        </div>

                      <h3 style="margin: 10px 0px 28px 0px">{% trans "Equipement" %}</h3>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.equipement.errors }}
                            <label for="id_message">{% trans "Equipement disponible" %} :</label>
                            {{ forms.chercheur.equipement }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.laboratoire.errors }}
                            <label for="id_sender">{% trans "Laboratoire" %} :</label>
                            {{ forms.chercheur.laboratoire }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.terrain.errors }}
                            <label for="id_cc_myself">{% trans "Terrain" %} :</label>
                            {{ forms.chercheur.terrain }}
                        </div>

                    <h3 style="margin: 10px 0px 28px 0px">{% trans "Valorisation et autres" %}</h3>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.valorisation.errors }}
                            <label for="id_message">{% trans "Valorisation et domaine de compétence" %} :</label>
                            {{ forms.chercheur.valorisation }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.partenaires.errors }}
                            <label for="id_sender">{% trans "Partenaires" %} :</label>
                            {{ forms.chercheur.partenaires }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.doctorants.errors }}
                            <label for="id_cc_myself">{% trans "Doctorants" %} :</label>
                            {{ forms.chercheur.doctorants }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.stagiaire.errors }}
                            <label for="id_cc_myself">{% trans "Stagiaire" %} :</label>
                            {{ forms.chercheur.stagiaire }}
                        </div>

                    <h3 style="margin: 10px 0px 28px 0px">{% trans "Publications" %}</h3>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.publicationsInternational.errors }}
                            <label for="id_message">{% trans "Nombre de publications de niveau international" %} :</label>
                            {{ forms.chercheur.publicationsInternational }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.publicationsAutre.errors }}
                            <label for="id_sender">{% trans "Autres publications" %} :</label>
                            {{ forms.chercheur.publicationsAutre }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.publicationsColloc.errors }}
                            <label for="id_cc_myself">{% trans "Nombre de publication ayant fait l'objet de publication dans actes de colloque" %} :</label>
                            {{ forms.chercheur.publicationsColloc }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.communication.errors }}
                            <label for="id_cc_myself">{% trans "Autres communications" %} :</label>
                            {{ forms.chercheur.communication }}
                        </div>

                     <h3 style="margin: 10px 0px 28px 0px">{% trans "Equipe de recherche" %}</h3>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.equipe.errors }}
                            <label for="id_message">{% trans "Etes-vous intéressé à créer ou intégrer une équipe de recherche?" %}</label>
                            {{ forms.chercheur.equipe }}
                        </div>
                        <div class="fieldWrapper">
                            {{ forms.chercheur.domaine.errors }}
                            <label for="id_sender">{% trans "Si oui dans quel domaine?" %}</label>
                            {{ forms.chercheur.domaine }}
                        </div>

                     <h3 style="margin: 10px 0px 28px 0px">{% trans "Thèse" %} <em style="font-size:12px">(ou tout autre travail de recherche &#8212; mémoire, HDR, etc. &#8212; encadré par un universitaire)</em></h3>
                            {% with forms.these as form %}
                            {% include "render_form.html" %}
                            {% endwith %}

                     <h3 style="margin: 10px 0px 28px 0px">{% trans "Publications (donner 10 références maximum, les plus représentatives de l'activité scientifique)" %}</h3>
                     <fieldset id="publications">

                               {{ forms.publications.management_form }}
                                    {% for form in forms.publications %}
                                    <fieldset style="border: 1px solid #aaaaaa; padding: 14px 0px 0px 10px; margin-bottom: 10px">
                                        {{ form }}
                                    </fieldset>
                                    {% endfor %}

                     </fieldset>

                     <h3 style="margin: 10px 0px 28px 0px">{% trans "Attestation" %}</h3>
                        <div class="fieldWrapper">
                            {{ forms.attestation.attestation.errors }}
                            {{ forms.attestation.attestation }}
                            <label for="id_sender" id="long">{{ forms.attestation.attestation.label_tag }}</label>
                        </div>

                    <p align="center"><input type="submit" name="env" value="Enregistrer le chercheur" /></p>
                </form>

           </div>

</div>

{% endblock %}

annuaire/templates/logged_out.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n pagination_tags %}

{% block Contenu %}
<div id="texte">
<!--<h3>Liste des chercheurs</h3>-->

    <div class="chercheur">
       <h3>{% trans "Déconnexion" %}</h3>
        <p>{% trans "Vous êtes maintenant déconnecté." %}</p>
        <p><a href="/">{% trans "Retour à l'accueil" %}</a>.</p>
    </div>

</div>
{% endblock %}

annuaire/templates/password_change_form.html
{% extends "base.html" %}
{% load i18n pagination_tags %}

{% block Contenu %}
<div id="texte">

<div class="chercheur">

	<h3>{% trans "Changement de mot de passe" %}</h3>
	<form method="post">{% csrf_token %}
        {% include "table_form.html" %}
        <input type="submit" name="Submit" value="Envoyer" class="bouton" />
    </form>
</div>

</div>
{% endblock %}

annuaire/templates/password_reset_form.html
{% extends "base.html" %}
{% load i18n pagination_tags %}

{% block Contenu %}
<div id="texte">

<div class="chercheur">
    <h3>{% trans "Demande de changement de mot de passe" %}</h3>
    <form method="post">{% csrf_token %}
    	{% if form.email.errors %}<ul class="errorlist"><li>{{ form.email.errors }}</li></ul>{% endif %}
        <p><label>{% trans "Veuillez entrer l'adresse électronique avec laquelle vous avez completé votre inscription." %}</label>{{ form.email }}</p>
        <input type="submit" name="Submit" value="Envoyer" class="bouton" />
    </form>
</div>

</div>
{% endblock %}

annuaire/templates/presentation.html
{% extends "auf_refonte/base_aruca.html" %}
{% load cms_tags staticfiles addCss%}

{% block 'contenu' %}
<!-- Espace contenu  -->
<!-- <div id="contenu"> -->
  {% static_placeholder "presentation" %}
<!-- </div> -->
<div class="row">
<video class="col-md-6 col-md-offset-3"src="{% static 'auf_refonte/images/VID_MLouis.MOV' %}" controls width="300px">
</video>
</div>
{% endblock %}